data_dir: data/
refresh_delay: 10
map:
  airplane:
    icon:
      url: "https://img.icons8.com/external-others-aquariid/64/ffffff/external-airplane-transportation-others-aquariid.png"
      width: 64
      height: 64
      anchorY: 64
  airport:
    icon:
      url: "https://img.icons8.com/ios-glyphs/30/fa314a/airport-building.png"
      width: 64
      height: 64
      anchorY: 64